apiVersion: v1
kind: Service
metadata:
  name: fshare-svc
spec:
  type: LoadBalancer
  loadBalancerIP: $loadBalancerIP
  selector:
    app: fshare-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fshare-svc-int
spec:
  selector:
    app: fshare-app
  ports:
  - port: 6100 
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fshare-app
spec:
  selector:
    matchLabels:
      app: fshare-app
  template:
    metadata:
      labels:
        app: fshare-app
    spec:
      containers:
      - name: fshare-app
        image: ${IMAGE}
        imagePullPolicy: Always
        env:
          - name: VERSION
            value: ${TAG}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: fshare-nfs-vol
            mountPath: '/mnt'
          - name: fshare-config-vol
            mountPath: '/opt/fshare/dist/config.json'
            subPath: config.json
      volumes:
        - name: fshare-nfs-vol
          persistentVolumeClaim:
            claimName: fshare-pvc
        - name: fshare-config-vol
          configMap:
            name: fshare-config


